language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t foxlol/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true foxlol/docker-react npm run test --bail

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-823523932962"
  bucket_path: "docker-react"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
