language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t foxlol/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true foxlol/docker-react npm run test --bail
